import Head from 'next/head'
import Intro from '../components/intro/Intro'





export default function Home() {


  return (
    <div>
      <Head>
        <title>Resume Builder</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Intro />
      </main>
    </div>
  )
}
